// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/xescugc/invoicer/template (interfaces: Repository)

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	gomock "github.com/golang/mock/gomock"
	template "github.com/xescugc/invoicer/template"
	reflect "reflect"
)

// TemplateRepository is a mock of Repository interface
type TemplateRepository struct {
	ctrl     *gomock.Controller
	recorder *TemplateRepositoryMockRecorder
}

// TemplateRepositoryMockRecorder is the mock recorder for TemplateRepository
type TemplateRepositoryMockRecorder struct {
	mock *TemplateRepository
}

// NewTemplateRepository creates a new mock instance
func NewTemplateRepository(ctrl *gomock.Controller) *TemplateRepository {
	mock := &TemplateRepository{ctrl: ctrl}
	mock.recorder = &TemplateRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *TemplateRepository) EXPECT() *TemplateRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method
func (m *TemplateRepository) Create(arg0 context.Context, arg1 *template.Template) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create
func (mr *TemplateRepositoryMockRecorder) Create(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*TemplateRepository)(nil).Create), arg0, arg1)
}

// Delete mocks base method
func (m *TemplateRepository) Delete(arg0 context.Context, arg1 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete
func (mr *TemplateRepositoryMockRecorder) Delete(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*TemplateRepository)(nil).Delete), arg0, arg1)
}

// Filter mocks base method
func (m *TemplateRepository) Filter(arg0 context.Context) ([]*template.Template, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Filter", arg0)
	ret0, _ := ret[0].([]*template.Template)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Filter indicates an expected call of Filter
func (mr *TemplateRepositoryMockRecorder) Filter(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Filter", reflect.TypeOf((*TemplateRepository)(nil).Filter), arg0)
}

// Find mocks base method
func (m *TemplateRepository) Find(arg0 context.Context, arg1 string) (*template.Template, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Find", arg0, arg1)
	ret0, _ := ret[0].(*template.Template)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Find indicates an expected call of Find
func (mr *TemplateRepositoryMockRecorder) Find(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Find", reflect.TypeOf((*TemplateRepository)(nil).Find), arg0, arg1)
}

// Update mocks base method
func (m *TemplateRepository) Update(arg0 context.Context, arg1 string, arg2 *template.Template) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update
func (mr *TemplateRepositoryMockRecorder) Update(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*TemplateRepository)(nil).Update), arg0, arg1, arg2)
}
